name: profanity_filter
description: Simple class to create filters that check and censor strings against profanity. A default English words list is provided.
version: 0.0.1
author: roshan<roshanrahman6399@gmail.com>
homepage: https://www.github.com/roshanrahman

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test:
